#!bash
#debug arguement:
#-T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_sim_time_local.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.0005 -So 0.5 -L 3 -RANDOM -SF 0.9 -W 600000 -TH 2


#java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.01 -So 0.5 -L 3 -LRU -SF 0.9 -W 600000 -TH 0 
java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.01 -So 0.5 -L 3 -TRUELRU -SF 0.9 -W 600000 -TH 0 -R

#java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 1 -I //Users//shengao//git//loadshedding//loadshedding//input//wind_speed_simTime.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.01 -So 0.5 -L 3 -CLOCKONE -SF 0.9 -W 600000 -TH 0
#java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 1 -I //Users//shengao//git//loadshedding//loadshedding//input//wind_speed_simTime.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.01 -So 0.5 -L 3 -CLOCKONE -SF 0.9 -W 600000 -TH 0 -R

#java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 1 -I //Users//shengao//git//loadshedding//loadshedding//input//wind_speed_simTime.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.01 -So 0.5 -L 3 -CLOCK -SF 0.9 -W 600000 -TH 0
#java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 1 -I //Users//shengao//git//loadshedding//loadshedding//input//wind_speed_simTime.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.01 -So 0.5 -L 3 -CLOCK -SF 0.9 -W 600000 -TH 0 -R

#java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 1 -I //Users//shengao//git//loadshedding//loadshedding//input//wind_speed_simTime.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.01 -So 0.5 -L 3 -CLOCKM -SF 0.9 -W 600000 -TH 0
#java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 1 -I //Users//shengao//git//loadshedding//loadshedding//input//wind_speed_simTime.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.01 -So 0.5 -L 3 -CLOCKM -SF 0.9 -W 600000 -TH 0 -R


#java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.0025 -So 0.5 -L 3 -CLOCKM -SF 0.9 -W 600000 -TH 0 -R
#java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 1 -I //Users//shengao//git//loadshedding//loadshedding//input//wind_speed_simTime.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.0005 -So 0.5 -L 3 -CLOCK -SF 0.9 -W 600000 -TH 0 -R
#java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 1 -I //Users//shengao//git//loadshedding//loadshedding//input//wind_speed_simTime.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.0005 -So 0.5 -L 3 -CLOCKONE -SF 0.9 -W 600000 -TH 0 -R
