#!bash


java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.9 -So 0.01 -L 3 -FIFOCLOCK -SF 0.1 -W 600000 -TH 15
java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.9 -So 0.01 -L 3 -FIFOCLOCK -SF 0.3 -W 600000 -TH 15
java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.9 -So 0.01 -L 3 -FIFOCLOCK -SF 0.5 -W 600000 -TH 15
java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.9 -So 0.01 -L 3 -FIFOCLOCK -SF 0.7 -W 600000 -TH 15
java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.9 -So 0.01 -L 3 -FIFOCLOCK -SF 0.9 -W 600000 -TH 15

java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.9 -So 0.01 -L 3 -FIFOLRU -SF 0.1 -W 600000 -TH 15
java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.9 -So 0.01 -L 3 -FIFOLRU -SF 0.3 -W 600000 -TH 15
java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.9 -So 0.01 -L 3 -FIFOLRU -SF 0.5 -W 600000 -TH 15
java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.9 -So 0.01 -L 3 -FIFOLRU -SF 0.7 -W 600000 -TH 15
java -jar -Xmx1024m loadshedding/target/loadshedding-0.0.1-SNAPSHOT-jar-with-dependencies.jar -T 21 -I //Users//shengao//git//loadshedding//loadshedding//input//epg_sim_time_local.csv -O //Users//shengao//git//loadshedding//loadshedding//input//log_with_oracle_3days.csv -OUT //Users//shengao//git//loadshedding//loadshedding//output// -Si 0.9 -So 0.01 -L 3 -FIFOLRU -SF 0.9 -W 600000 -TH 15
